### ISSUE TITLE
调整时区时 agenda 没有及时更新

### ISSUE THREAD

**Issue by yejingchen** [futurenda/user-voice#2]
**环境**
  Android 7.1.1 魔趣
  chrome stable 56.0.292487
  ZJUWLAN

**问题**
  第一次打开 futurenda 时没有正确获取我的时区，此时是 America/Chicago 时区。在北京时间半夜（在我设置的 sleep time 00:00 之后）在 agenda 新建一个 task，由于 Chicago 时间是白天，这个 task 会马上开始进行。此时去设置时区为 Asia/Shanghai，回到 agenda 后上述 task仍在进行而没有自动随时区调整。关闭再重新打开自动睡眠时间也不一定能更新 agenda。之后不知道发生了什么 agenda 出现了加载的图标，agenda 才根据新时区调整了 task。

**Comment by fnlctrl** [comment]
America/Chicago比较谜..你试一下在chrome里F12 console输入```Intl.DateTimeFormat().resolvedOptions().timeZone```
试试 看一下结果是啥

**Comment by zenozeng** [comment]
Fixed in API v0.27.58. (Master CI Build 1981)
